### ISSUE TITLE
New hackers I've ran into

### ISSUE THREAD

**Issue by ghost** [qfoxb/tf2bd-lists#3]
Each of these videos in my playlist includes proof + steam IDs of all the people hacking. Not all of the proof is definitive (mainly Spotty Cat and 1 of the potential hackers, pootisfile, from the DeputyDong video, maybe the Felix Argyle one?), but the rest of it is.

[Playlist linked here.](https://www.youtube.com/playlist?list=PLUT9gHeELz4e22aO67cKjTDJ8QTcYuP9-)

**Comment by qfoxb** [comment]
Will start adding these later tonight
