### ISSUE TITLE
Discussion, should the discord.gg link auto flag be removed?

### ISSUE THREAD

**Issue by qfoxb** [qfoxb/tf2bd-lists#4]
Should i remove the discord.gg filter from the rule list? I've had multiple legitimate players get flagged because they were trying to send a discord link to someone who wanted it.  

The bots don't seem to be much of an issue right now.

**Comment by fluteds** [comment]
I'd say if we could remove the `discord.gg/*` wildcard and have it only recognizing the invite code of known promo invites `/XXXX` that would be ideal but I'm not sure if that's possible or not.

**Comment by qfoxb** [comment]
Yeah, that would be possible, is there a list of known promo discord invites?

**Comment by fluteds** [comment]
> Yeah, that would be possible, is there a list of known promo discord invites?

Not that I'm aware of. I think this might be a scrape down the list of well known block lists and picking them out.

**Comment by qfoxb** [comment]
I think for now i'm just going to remove the discord.gg/* wildcard. If you know any known promo links or have anything else to add please feel free to open a Pull Request or comment on this issue.

**Comment by ghost** [comment]
The YouTube wildcard should go too imo. I post youtube links in chats of hackers when I run into them if I've recorded them, so this would inadvertently flag people like me.
