### ISSUE TITLE
More hackers I've ran into

### ISSUE THREAD

**Issue by ghost** [qfoxb/tf2bd-lists#5]
[JangosHere](https://www.youtube.com/watch?v=sMd5l7yRKKU)
[Maurve and hani ma](https://www.youtube.com/watch?v=lx2vN6XPUOY)
[muchacha_spaghetti29 and Dirk](https://www.youtube.com/watch?v=-Gr2ENFc0Y4)
[beltislegit](https://www.youtube.com/watch?v=x5sBBn23Xvo)
[Bimbo Deer Milf](https://www.youtube.com/watch?v=RgAml-2ICOI)

All their steamIDs are in the descriptions.

Woops, shoulda done it as a blank issue instead. My bad

**Comment by qfoxb** [comment]
Will look at this later

**Comment by qfoxb** [comment]
Closing bc user deleted github account and their youtube account
